version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/mydatabase"
    volumes:
      - .:/usr/src/app

volumes:
  mysql-data:
